### ISSUE TITLE
Weird formatting in error.c file

### ISSUE THREAD

**Issue by Ullaakut** [NySwann/NCurses_Sokoban#1]
https://github.com/NySwann/NCurses_Sokoban/blob/master/src/error.c

The formatting of function names is weird, the two first functions defined have 12 spaces between the return type and the function name while the last one has only 4 of them.

**Comment by NySwann** [comment]
Haha, that's why emacs is so fun. When you copy/paste, it replaces tab with spaces ... Anyway! I'll correct this, thanks :)
