### ISSUE TITLE
find_player quits without warnings or reason if a player is found twice

### ISSUE THREAD

**Issue by Ullaakut** [NySwann/NCurses_Sokoban#2]
```
static t_point	find_player(t_map *map)
{
  size_t	x;
  size_t	y;
  t_point	player;
  char		found;

  found = y = 0;
  while (y < map->height)
    {
      x = 0;
      while (x < map->width)
	{
	  if (map->tiles[y][x] == PLAYER_CHAR)
	    {
	      if (found)
		exit(84);
	      found = 1;
	      player.x = x;
	      player.y = y;
	    }
	  x++;
	}
      y++;
    }
  return (player);
}
```

Maybe this is supposed to be the expected behaviour, to exit with a 84 status, but I guess it is not and you just wanted to quit if a player was found twice, since it's supposed to be impossible. 

In my opinion, the best in this case is to print a warning message (as this should certainly not stop your program) and go on with the first found player.

**Comment by NySwann** [comment]
Indeed, that seems to be a much better solution to this problem!
I'll add this, thanks ! :)
